---
- hosts: webservers
  become: yes
  tasks:
  - name: i want execute linux command 
    command: hostname -f
    register: myresult
  
  - name: i want display myresult
    debug:
       msg: "{{myresult}}"
