---
- hosts: webservers
  become: yes
  tasks:
  - name: 1st task instal git
    apt:
      name: git
      state: present

  - name: 2ns task instal tree
    apt:
      nameeeee: tree
      state: present
    ignore_errors: yes

  - name: 3rd task  instal wget
    apt:
      name: wget
      state: present