---
- hosts: webservers
  become: yes
  tasks:
  - name: "{{mywebtext}}"
    apt:
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"
  - name: i want restart my webserver on ubuntu16
    service:
      name: "{{mywebpackonubuntu}}"
      state: restarted
    when: ansible_os_family =="Debian"

  - name: i want to install webserver on RedHat
    yum:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family =="RedHat"

  - name:  i want to start webserver RedHat
    service:
      name: "{{mywebpackonredhat}}"
      state: started
    when: ansible_os_family =="RedHat"

